//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace O10.Web.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("O10.Web.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed for the account with accountId &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_ACCOUNT_AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with id {0} not found.
        /// </summary>
        internal static string ERR_ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofs of value knowledge and binding have different sizes at Associated Attribute with the scheme {0}.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_MALFORMED {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_MALFORMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proofs of Associated Attribute with the scheme {0} are missing.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_MISSING {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of source commitments of proofs of Associated Attribute with the scheme {0} was not found.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_SOURCE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_SOURCE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of binding to Root of the Associated Attribute with the scheme {0} is incorrect.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_TO_BINDING {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_TO_BINDING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proof of value knowledge of the Associated Attribute with the scheme {0} is incorrect.
        /// </summary>
        internal static string ERR_ASSOCIATED_PROOF_TO_VALUE_KNOWLEDGE {
            get {
                return ResourceManager.GetString("ERR_ASSOCIATED_PROOF_TO_VALUE_KNOWLEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate with the thumbprint &apos;{0}&apos; not found at storage &apos;{1}&apos;..
        /// </summary>
        internal static string ERR_CERT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_CERT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commitment eligibility verification failed.
        /// </summary>
        internal static string ERR_COMMITMENT_ELIGIBILITY_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_COMMITMENT_ELIGIBILITY_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execution context not started yet for the account with accountId &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_EXECUTIONCONTEXT_NOTSTARTED {
            get {
                return ResourceManager.GetString("ERR_EXECUTIONCONTEXT_NOTSTARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to transfer Root Attribute.
        /// </summary>
        internal static string ERR_FAILED_TRANSFER_ROOT_ATTR {
            get {
                return ResourceManager.GetString("ERR_FAILED_TRANSFER_ROOT_ATTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matching image to registration &apos;{0}&apos; failed.
        /// </summary>
        internal static string ERR_INHERENCE_MATCHING_FAILED {
            get {
                return ResourceManager.GetString("ERR_INHERENCE_MATCHING_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inherence registration proofs are incorrect.
        /// </summary>
        internal static string ERR_INHERENCE_REGISTRATION_PROOFS_INCORRECT {
            get {
                return ResourceManager.GetString("ERR_INHERENCE_REGISTRATION_PROOFS_INCORRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Root Attribute Scheme defined for the issuer &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_NO_ROOT_SCHEME_DEFINED {
            get {
                return ResourceManager.GetString("ERR_NO_ROOT_SCHEME_DEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation proofs were not provided.
        /// </summary>
        internal static string ERR_NO_VALIDATION_PROOFS {
            get {
                return ResourceManager.GetString("ERR_NO_VALIDATION_PROOFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protection Attribute verification failed.
        /// </summary>
        internal static string ERR_PROTECTION_ATTR_VERIFICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_PROTECTION_ATTR_VERIFICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find any SamlIdpService that can serve for entity id &apos;{0}&apos;..
        /// </summary>
        internal static string ERR_SAML_IDP_SERVICE_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SAML_IDP_SERVICE_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to find session of scenario {0} for user {1}..
        /// </summary>
        internal static string ERR_SCENARIO_SESSION_NOT_FOUND {
            get {
                return ResourceManager.GetString("ERR_SCENARIO_SESSION_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Proofs were incorrect.
        /// </summary>
        internal static string ERR_SP_AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("ERR_SP_AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received account with accountId &apos;{0}&apos; with unexpected type &apos;{0}&apos;.
        /// </summary>
        internal static string ERR_UNEXPECTED_ACCOUNT_TYPE {
            get {
                return ResourceManager.GetString("ERR_UNEXPECTED_ACCOUNT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation of proof failed: {0}.
        /// </summary>
        internal static string ERR_VALIDATION_PROOF_FAILED {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_PROOF_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation proofs were not complete for {0}.
        /// </summary>
        internal static string ERR_VALIDATION_PROOFS_NOT_COMPLETE {
            get {
                return ResourceManager.GetString("ERR_VALIDATION_PROOFS_NOT_COMPLETE", resourceCulture);
            }
        }
    }
}
