name: ci

on:
  push:
    branches: master

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        run: |
          echo "Changing folder to O10.Web.Server"
          cd O10.Web.Server
          ls
          docker build O10.Web.Server --tag muaddibco/o10portal:maxathon
          docker push muaddibco/o10portal:maxathon
